### ISSUE TITLE
CCBV design

### ISSUE THREAD

**Issue by rleonid** [c-cube/ocaml-containers#113]
The design of CCBV doesn't track the desired size of a bitvector and implicitly rounds it to the nearest word size. This makes it impossible, AFAIK, to write some useful functions such as `negate` or `difference`. Would you welcome a change that keeps track of the specified length and then the burden of checking it or would you prefer the current implementation?

**Comment by c-cube** [comment]
I would certainly! In particular some of the current functions are not accurate on the last word (e.g. iterators). As I said elsewhere, the basic functions work well right now, and adding a `length` field would not hurt them, but for newer/more subtle functions testing is important because there often are corner cases. Of course I can add some tests myself if you PR the API changes.

**Comment by c-cube** [comment]
See #116 for a work in progress refactoring. More tests are needed.

**Comment by c-cube** [comment]
closed by #117
