### ISSUE TITLE
Random.sample_without_replacement is named incorrectly

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#130]
this may be a nitpick, but i think this function does not do what it says it does. iiuc, the function samples from a generator and compares with the already produced values ensuring that one gets a different one.

sampling without replacement usually refers to sampling from a finite set of elements without replacing them. unlike random generators the finite set can be exhausted. now you could say, take the limit of an infinitely large set. but the set can also contain repeated elements. so one does not in general get different outcomes on successive draws. 

i think this function is problematic in general:
```
let gg = Random.choose_return [true; false];;
let gr = Random.sample_without_replacement 2 gg;;
```
here i get always `[false;true]` in this order? 

and 
```
let gr = Random.sample_without_replacement 3 gg;;
```
is an infinite loop.

**Comment by c-cube** [comment]
- I don't know about the name. I think it was picked by @Octachron. Note that for me, a "set" cannot contain repeated elements by definition.
- it always returns `[false; true]` because internally elements are stored in a set. The elements of the sample are random, but their order within the sample is not.
- well you cannot pick 3 distinct elements from this generator? What would be a correct answer?

**Comment by nilsbecker** [comment]
i see. i was primed by the classical statistics setup of 'drawing repeatedly from an urn with m white balls and N-m black balls'. if you draw with replacement you get black and white with probabilities m/N and (N-m)/N always. if you draw without replacement, after you've exhausted white for example, you get black with prob. 1. so i guess it's semantics. 

the infinite loop is of course correct behavior for the definition of the function. i just find the definition itself unintuitive. but i guess it's there for a reason! maybe `sample_subset` or something like that would have been a possible name?

i don't know if this is in the scope of `Random` but what i would find useful is a random generator `sample : ?weights:float list -> n -> 'a list -> 'a list t` which samples n values from a finite list, and a counterpart `sample_without_ ?weights:float list -> n -> 'a list -> 'a list t` which samples without replacement and gives a list of length at most as long as the element list.

**Comment by Octachron** [comment]
I think that `sample_subset` would be a fine name for sampling uniformly a fixed-size subset from an explicit finite sample space Ω.

Nevertheless, I still think that `sample_without_replacement` is an appropriate name here since the sampling is not uniform and depends on the probability measure μ associated with the generator. 
In particular,  I thought  that the name conveyed the point that the function is sampling from a sample space Ω removing each element after each draw.

Note that the main difference from the classical black and white urn example is that all elements are considered distinguables rather than having k undistinguable black balls and l undistinguable white balls.

**Comment by nilsbecker** [comment]
> the main difference from the classical black and white urn example is that all elements are considered distinguables

i think i understand. the two setups become the same when

1.  the probabilities are uniform and there is exactly one ball of each type in the urn, or

2. the probabilities are not necessarily uniform but are modeled by placing amounts of balls of each type proportional to the probability into the urn; after one draw, all remaining balls of the just drawn type have to be removed from the urn.

the way you described it, the name does make sense - each possible outcome is removed after it has been seen. however for me 'replacement' still evokes the physical act of replacing an item (as opposed to a category of possible outcomes), and the naming to me feels non-standard.

in any case, i think the doc string is clear on what it does so probably no good reason to change the api. 

as for the sample functions i proposed: `sample` would be redundant with `pick_list` if that allowed weights. `sample_without_` might still be worthwhile, with a name that does not clash...

**Comment by c-cube** [comment]
Right, `pick_list` is a bit limited. I confess I don't often use `CCRandom` because in general, I need randomness for property-based testing and [qcheck](/c-cube/qcheck) already has many more generators. It might be worth it for you, @nilsbecker, to look at `QCheck.Gen` or https://github.com/gasche/random-generator.

**Comment by nilsbecker** [comment]
thanks, i'll have a look. in the past i have used the gsl bindings for that...

**Comment by c-cube** [comment]
`sample_without_duplicates` maybe? I could add an alias and deprecate the old name.

**Comment by nilsbecker** [comment]
`sample_without_duplicates` sounds good to me.
