### ISSUE TITLE
roadmap wrt sequence / Seq

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#231]
containers supports conversions to `Sequence.t` from the sequence library. it seems that the standard library's `Seq.t` will supersede use of sequence in the future. if that is correct, would it make sense to plan to support `Seq` in containers?

**Comment by c-cube** [comment]
I'm not sure exactly how to handle `seq`, tbh. There are several issues:

- normally, containers provides the same signature (±) on every version of OCaml it supports. For `seq` that'd be hard to do because you can't write `Hashtbl.to_seq` reasonably efficiently without knowing the internal structure of the hashtable. Same for Map/Set.
- We'd probably need to break compatibility (and a *lot* of existing code, at least my own projects) if we're to repurpose `to_seq/of_seq`.

These points seem non trivial, and need to be addressed before containers support Seq properly.

**Comment by nilsbecker** [comment]
i can see that it's going to be tricky since it's deeply integrated. a probably bad alternative would be to provide both, adding `to_oseq` etc everywhere. or, providing two alternative modules which interoperate with sequence or Seq, respectively. both sound like quite some overhead? maybe code duplication could be reduced by splitting off the common functions...

**Comment by c-cube** [comment]
having `Seq` submodules honestly seems like the best option for problem 2 (as well as `Sequence` submodules to provide a migration path from toplevel `to_seq/of_seq`). Removing all support for sequence is a strong "no" as it's still a really fast operation that I need in many libs :p

**Comment by nilsbecker** [comment]
actually i was not aware of performance differences between Seq and sequence! maybe that would be something to document in the sequence docs?

**Comment by pmetzger** [comment]
@c-cube You can probably get volunteers to help write documentation if you solicit for such help.

**Comment by c-cube** [comment]
@pmetzger here you go :p 
<https://github.com/c-cube/sequence/issues/19>

**Comment by c-cube** [comment]
update:

- add `{to,of}_iter` with the same implementation as `{to,of}_seq`
- deprecate `*_seq`

then in 3.0:

- make `{to,of}_seq` compatible with the stdlib, using `Seq.t`
