### ISSUE TITLE
add conversion from/to CCSexp in most modules

### ISSUE THREAD

**Issue by c-cube** [c-cube/ocaml-containers#64]

**Comment by kwshi** [comment]
How would you serialize a string?  Glancing at the CCSexp interface, it doesn't appear that quoted/escaped strings are available, so that would prevent reliable conversion to/from CCSexp.  As for lists/arrays/other container types, are you thinking about a signature like `to_sexp : ('a -> Sexp.t) -> 'a list -> Sexp.t`?

**Comment by c-cube** [comment]
```ocaml
# print_endline @@ CCSexp.to_string (`List [`Atom "42 spaces"; `Atom "foo bar()"]);;
("42 spaces" "foo bar()")
```

besides there isn't a real fixed type anymore, this probably should be closed, it's been years.
