### ISSUE TITLE
merlin can't locate definition or signature of containers functions 

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/ocaml-containers#80]
if i try `MerlinLocate` on e.g. Containers.List.random_choose i get `'CCList.random_choose' seems to originate from 'CCList' whose ML file could not be found`. it would be great if this could get me to the function definition or signature to find the doc string. as it is i always have to navigate to the containers docs on the internet to have access to documentation. this may also be a merlin shortcoming, i'm not sure!

**Comment by c-cube** [comment]
I will investigate, indeed, I miss this too but never paid too much attention. Thanks.

**Comment by c-cube** [comment]
I asked the merlin gurus, and apparently it's because the `.cmt` files are installed, so merlin (by default) tries to jump to the actual definition, looks for the corresponding `.ml` file (which does not exist), and fails, even though the `.mli` is present. I will see if I can get oasis not to install the `.cmt`.

**Comment by c-cube** [comment]
Well it's really a problem in merlin (cannot fallback on .mli if it cannot find the .ml) OR in oasis (which installs .cmt without .ml), so I can't do much, sorry.
